name: F3 CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Cygwin (Windows)
      if: matrix.os == 'windows-latest'
      uses: cygwin/cygwin-install-action@v2
      with:
        platform: x86_64
        packages: gcc-core make libargp-devel
        install-dir: C:/cygwin64

    - name: Setup environment (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        echo "Cygwin path: /cygdrive/c/cygwin64/bin"
        export PATH="/cygdrive/c/cygwin64/bin:$PATH"
        gcc --version
        make --version

    - name: Setup environment (Linux)
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev libparted-dev

    - name: Build
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
            make CC="gcc" EXTRA_CFLAGS="-DWINDOWS_COMPAT" all
        else
            make all
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: f3-${{ matrix.os }}
        path: |
          *.exe
          f3*
